// Points the app at the local Supabase: writes .env.local (git-ignored) from `npx supabase status`.
// `npm run dev` then runs in cloud mode against your own machine. Delete .env.local to go back to the demo.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
const st = JSON.parse(execSync("npx supabase status -o json", { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] }));
// a phone on the same Wi-Fi reaches this machine by its LAN address, not 127.0.0.1 — pass --lan to use it
const lan = process.argv.includes("--lan") ? (await import("node:os")).networkInterfaces() : null;
const ip = lan && Object.values(lan).flat().find((i) => i && i.family === "IPv4" && !i.internal)?.address;
const url = ip ? st.API_URL.replace("127.0.0.1", ip) : st.API_URL;
writeFileSync(new URL("../../.env.local", import.meta.url), `# local Supabase (generated by scripts/db/env-local.mjs — not committed)\nVITE_SUPABASE_URL=${url}\nVITE_SUPABASE_PUBLISHABLE_KEY=${st.PUBLISHABLE_KEY || st.ANON_KEY}\n`);
console.log(`.env.local → ${url}`);
